language : node_js
node_js:
 - "10"
 - "9"

os:
 - linux

 branches:
  only:
    - master


deploy:
  provider: npm
  email: 659721336@qq.com
  api_key: "${NPM_TOKEN}"
  skip_cleanup: true
  on:
    branch: master